# 谁是卧底 插件配置

# 游戏词库
# 在这里添加你想要的词语，格式如下：
# - civilian: "平民词"
#   spy: "卧底词"
words:
  - civilian: "可乐"
    spy: "雪碧"
  - civilian: "椅子"
    spy: "凳子"
  - civilian: "米饭"
    spy: "面条"
  - civilian: "太阳"
    spy: "月亮"
  - civilian: "老师"
    spy: "学生"
  - civilian: "眼睛"
    spy: "眼镜"
  - civilian: "牛奶"
    spy: "豆浆"
  - civilian: "西瓜"
    spy: "冬瓜"
  - civilian: "高铁"
    spy: "火车"
  - civilian: "狗"
    spy: "猫"
  - civilian: "薯片"
    spy: "薯条"
  - civilian: "饺子"
    spy: "包子"
  - civilian: "键盘"
    spy: "鼠标"
  - civilian: "红色"
    spy: "蓝色"
  - civilian: "茶"
    spy: "咖啡"
  - civilian: "电影"
    spy: "电视剧"
  - civilian: "书"
    spy: "本子"
  - civilian: "鸡你太美"
    spy: "只因你太美"
  - civilian: "奥利奥"
    spy: "奥利给"
  - civilian: "凡尔赛"
    spy: "凡尔赛宫"
  - civilian: "爷青回"
    spy: "爷青结"
  - civilian: "网抑云"
    spy: "网易云"
  - civilian: "苦力怕"
    spy: "爬行者"
  - civilian: "原神启动"
    spy: "玩原神玩的"
  - civilian: "变身"
    spy: "变色"
  - civilian: "末影人"
    spy: "末影螨"
  - civilian: "附魔台"
    spy: "锻造台"
  - civilian: "幻翼"
    spy: "幻术师"
  - civilian: "流浪商人"
    spy: "流浪者"
  - civilian: "潮涌核心"
    spy: "海洋之心"
  - civilian: "钻石镐"
    spy: "下界合金镐"
  - civilian: "华强买瓜"
    spy: "老农卖瓜"
  - civilian: "快乐星期五"
    spy: "疯狂星期四"
  - civilian: "细狗"
    spy: "藏獒"
  - civilian: "电动鞋刷"
    spy: "电动牙刷"
  - civilian: "臭豆腐"
    spy: "粪便"
  - civilian: "睫毛"
    spy: "眉毛"
  - civilian: "茶"
    spy: "尿"
  - civilian: "跳伞"
    spy: "裸奔"
  - civilian: "跳楼"
    spy: "蹦极"
  - civilian: "尖叫"
    spy: "脉动"
  - civilian: "恐怖片"
    spy: "鬼屋"
  - civilian: "梨子"
    spy: "苹果"
  - civilian: "火箭"
    spy: "箭矢"
  - civilian: "婚礼"
    spy: "葬礼"
