name: WhosTheSpy
version: '1.0'
main: org.encinet.whosTheSpy.WhosTheSpy
api-version: '1.18'
authors: [ Noctiro ]
website: https://github.com/encinet
commands:
  spy:
    description: "Who's The Spy main command"
    usage: "/spy"
